### ISSUE TITLE
Opposite sorting while selecting multiple marks

### ISSUE THREAD

**Issue by amirziv418** [tableau/extension-quick-what-if#10]
Hi, The issue occurs while selecting more than a single mark on the Tableau worksheet (the Viz type is irrelevant).
The values on the extension are opposite to the (dimension) values on the Tableau worksheet. It's confusing for the end-user and could easily cause wrong results and false insights, which is precisely the opposite of the extension's purpose.
Can you check how to fix it? Thanks!
Amir

**Comment by bcantoni** [comment]
After internal review we determined that unfortunately we are not going to fix this.
