### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by kachilles140** [tableau/extension-quick-what-if#5]
Dear all,

the extension is running great! I appreciate your work here. :-)

Unfortunately I ran into a problem regarding the default values. On default, every value is 0. 
I want to set a custom value, based on another column. 
Any idea how to get this thing working?

Thanks in advance
Kevin

**Comment by KeshiaRose** [comment]
Thanks for the idea @kachilles140 I've marked this as a feature request and hope to add it in the future!
