### ISSUE TITLE
Can you fix on multiple dimensions/dates?

### ISSUE THREAD

**Issue by njleather** [tableau/extension-quick-what-if#7]
Hello,

As in the example showcased in the what-if example, is it possible to fix the pop-up on both category and date for example?
When I apply the extension to my own use case, I'm struggling to identify how I can alter the level of detail in the extension.

Thank you,
Nathan

**Comment by KeshiaRose** [comment]
Hi @njleather, to do that you could create a combined calculation with category and date and then use that as the basis of your inputs in the extension. Would that work for your use case?

**Comment by njleather** [comment]
> Hi @njleather, to do that you could create a combined calculation with category and date and then use that as the basis of your inputs in the extension. Would that work for your use case?

Hi Keshia. Thanks for getting back to me. Does this combined calculation have to be in the data set before connecting to Tableau or can it be made as a calculated field?
